# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to a recent 7.x version
  - 7.0
  # aliased to a recent 7.x version
  - 7.1

install:
# Install PHPCS
  - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar php phpcs.phar -h
  - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar php phpcbf.phar -h

script:
  - phpenv rehash
  - phpcs .

# configure notifications (email, IRC, campfire etc)
notifications:
  email: "yvesbellenger@hotmail.com"