# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to a recent 7.x version
  - 7.0
  # aliased to a recent 7.x version
  - 7.1

install:
# Install PHPCS
  - composer global require "squizlabs/php_codesniffer=*"

script:
  - phpenv rehash
  - phpcs .

# configure notifications (email, IRC, campfire etc)
notifications:
  email: "yvesbellenger@hotmail.com"
